#!/bin/bash

BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`

battery() {
	cat /sys/class/power_supply/${BAT}/capacity
}
battery_stat() {
	cat /sys/class/power_supply/${BAT}/status
}

battery_icon() {
    capacity=$(cat /sys/class/power_supply/${BAT}/capacity)
    
    if [[ "$capacity" -gt "75" ]]; then
        echo ""
    fi

    echo $capacity
}

if [[ "$1" == "--bat" ]]; then
	battery
elif [[ "$1" == "--bat-st" ]]; then
	battery_stat
elif [[ "$1" == "--icon" ]]; then
    battery_icon
fi

