#!/bin/bash

percent=0
muted="on"

get_volume() {
    percent=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print int(($2/1.5)*100) }')
}

get_muted() {
    muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print $3 }')
}

get_icon() {
    if [[ "$muted" == "[MUTED]" ]]; then
        echo "󰝟 "
        return
    fi

    if [[ "$percent" -gt "75" ]]; then
        echo "󰕾 "
    elif [[ "$percent" -gt "35" ]]; then
        echo "󰖀 "
    elif [[ "$percent" -gt "0" ]]; then
        echo "󰕿 "
    elif [[ "$percent" -eq "0" ]]; then
        echo "󰝟 "
    fi
}

if [[ "$1" == "--volume" ]]; then
    get_volume
    get_muted
    echo "$percent"

elif [[ "$1" == "--icon" ]]; then
    get_volume
    get_muted
    get_icon
fi
