#!/usr/bin/python

import subprocess
import os
import socket
import json

def get_workspaces(activeWorkspace):
    cmd = "hyprctl workspaces -j"
    workspaces = json.loads(subprocess.getoutput(cmd))
    icons = []

    for w in workspaces:
        if int(w["id"]) >= 0:
            icons.append("")
    
    if activeWorkspace < len(icons):
        icons[activeWorkspace] = ""
    else:
        icons[-1] = ""

    prompt = f"(box :class \"works\" :spacing 5 :space-evenly false (label :text \""
    
    for i in icons:
        prompt += i + "  "

    prompt += "\" ))"

    subprocess.run(f"echo '{prompt}'", shell=True)

        # print(w["lastwindowtitle"])
    # workspaces = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    # print(workspaces.stdout.read())

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
server_address = f'/tmp/hypr/{os.environ["HYPRLAND_INSTANCE_SIGNATURE"]}/.socket2.sock'
sock.connect(server_address)

while True:
    new_event = sock.recv(4096).decode("utf-8")
    
    for item in new_event.split("\n"):
        if "workspace>>" == item[0:11]:
            workspaces_num = item[-1]
            get_workspaces(int(workspaces_num)-1)
