#!/bin/bash

## Files and cmd
# EWW="eww -c $HOME/.config/eww/bar"
#
# ## Run eww daemon if not running already
# if [[ ! `pidof eww` ]]; then
# 	${EWW} daemon
# 	sleep 1
# fi

eww open bar -c $HOME/.config/eww/bar/

num_monitors=$(hyprctl monitors | grep "Monitor" | wc -l)

if [ $num_monitors -ge 2 ]
then
    eww open bar2 -c $HOME/.config/eww/bar/
fi
